name: CI
on:
  push:
    branches:
      - dev
  pull_request:
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        description: Creates a draft release
        required: false

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build and test app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleDebug

      - name: Create Release
        uses: actions/upload-artifact@v2
        with:
          name: Tachiyomi
          path: app/build/outputs/apk

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Tachiyomi
