name: CI
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build and test app
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug :domain:jvmTest :domain:jacocoTestReport
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload test coverage
        uses: codecov/codecov-action@v1

      - name: Publish packages to Maven Central
        run:  |
          echo "${{ secrets.OSSRH_GPG_SECRET_KEY }}" > ~/.gradle/signing.gpg
          gradle publish \
            -Psigning.keyId=${{ secrets.OSSRH_GPG_SECRET_KEY_ID }} \
            -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            -Psigning.secretKeyRingFile=$(echo ~/.gradle/signing.gpg)
          rm ~/.gradle/signing.gpg
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
